#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    afterHelm: 20
EOF
}

function __main__() {
  if secrets=$(kubectl get storageclass -o json | jq '.items[] | select(.provisioner == "kubernetes.io/rbd") | .parameters.userSecretName' -r) ; then
    for secret in $secrets ; do
      if ! kubectl -n d8-openvpn get secret $secret > /dev/null 2> /dev/null ; then
        kubectl get secret --all-namespaces --sort-by='.metadata.creationTimestamp' -o json | jq '[.items[] | select(.metadata.name == "'$secret'")][-1] | del(.metadata.annotations,.metadata.uid,.metadata.resourceVersion,.metadata.selfLink,.metadata.creationTimestamp) | .metadata.namespace = "d8-openvpn"' | kubectl create -f -
      fi
    done
  fi
}

hook::run $@
