#!/bin/bash

# Copyright 2021 Flant JSC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /deckhouse/shell_lib.sh

function __config__() {
  cat << EOF
    configVersion: v1
    beforeHelm: 10
EOF
}

function __main__() {
  KUBE_NODES_INFO=$(kubectl get nodes -o json)
  KUBE_SERVICE_NETWORK=$(awk '{gsub("\\.", " "); print $1"."$2"."$3".0/255.255.0.0"}' <<< $KUBERNETES_SERVICE_HOST)
  KUBE_POD_NETWORK=$(jq -r '.items[].spec.podCIDR' <<< $KUBE_NODES_INFO | awk '{gsub("\\.", " ");print $1"."$2".0.0/255.255.0.0"}' | head -n1 || true)
  KUBE_NODES_IPS=$(jq -r '.items[].status.addresses | .[] | select(.type == "InternalIP" and .address != "") | .address' <<< $KUBE_NODES_INFO | xargs printf ",\"%s/255.255.255.255\" ")

  if ! values::has 'openvpn.pushToClientRoutes' ; then
    values::set --config openvpn.pushToClientRoutes "[\"$KUBE_SERVICE_NETWORK\",\"$KUBE_POD_NETWORK\"$KUBE_NODES_IPS]"
  fi
}

hook::run $@
