{{- if and (.Values.prometheus.internal.deployDexAuthenticator) (.Values.prometheus.internal.alertmanagers.internal) }}
---
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: "alertmanager"
  namespace: "d8-monitoring"
  {{- include "helm_lib_module_labels" (list . (dict "app" "dex-authenticator" "name" "alertmanager" )) | nindent 2 }}
spec:
  applicationDomain: {{ include "helm_lib_module_public_domain" (list . "alertmanager") }}
  {{- if (include "helm_lib_module_https_ingress_tls_enabled" .) }}
  applicationIngressCertificateSecretName: {{ include "helm_lib_module_https_secret_name" (list . "ingress-tls") }}
  {{- end }}
  applicationIngressClassName: {{ include "helm_lib_module_ingress_class" . | quote }}
  signOutURL: "/logout"
  {{- with .Values.prometheus.auth.allowedUserGroups }}
  allowedGroups:
  {{- . | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
